


## This config file contains all the configuration of the files like file_paths, folder_path, urls
## yaml is a human-readable language which is easy to exchange the data between the different programs

artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_URL : 'https://github.com/MadanuAugustin/IrisFlowerClassification_with_MLflow/raw/main/Notebook/archive%20(2).zip'
  local_data_file : artifacts/data_ingestion/raw-data.zip
  unzip_dir : artifacts/data_ingestion/


data_validation:
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/Iris.csv
  STATUS_FILE : artifacts/data_validation/status.txt


data_transformation:
  root_dir : artifacts//data_transformation
  data_path : artifacts//data_ingestion//Iris.csv


model_trainer:
  root_dir : artifacts//model_trainer
  train_data_path : artifacts//data_transformation//transformed_train_data.csv
  test_data_path : artifacts//data_transformation//transformed_test_data.csv
  model_name : model.joblib